name: Valgrind

 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

 

jobs:
  build:

 

    runs-on: ubuntu-latest

 

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: Install Cunit
      run: sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: make all
      run: |
       make all -C 99002652/
       chmod +x ./99002652/all.out
       valgrind ./99002652/all.out
